/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.cheart.do12306.app.view;

import android.widget.CompoundButton;
import android.widget.CheckBox;

import java.util.List;

import android.view.View;
import android.widget.SimpleAdapter;
import android.content.Context;
import java.util.Map;
import android.view.ViewGroup;
import android.view.LayoutInflater;

import java.util.Map;

import android.support.v7.app.ActionBarActivity;
import android.widget.Button;
import android.widget.ListView;
import android.widget.TableLayout;
import android.widget.TextView;

import java.util.HashMap;
import java.util.ArrayList;

import com.cheart.do12306.app.R;
import com.cheart.do12306.app.client.CommunalData;

import java.util.Iterator;

import com.cheart.do12306.app.domain.Passenger;

import android.util.Log;

import com.cheart.do12306.app.domain.BaseQueryLeft;
import com.cheart.do12306.app.domain.BaseData;

import android.widget.ListAdapter;
import android.widget.AdapterView;
import android.os.Bundle;
import android.content.Intent;

import java.io.Serializable;

import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.widget.Toast;

import com.cheart.do12306.app.adapter.SubmitOrderTicketInfoAdapter;
import com.cheart.do12306.app.task.SubmitOrderTask;

public class SubmitOrderActivity extends ActionBarActivity {
    public static String CAN_SEAT_TYPE = null;
    public static final String[] FROM = null;
    public static final String NAME_1 = "name_1";
    public static final String NAME_2 = "name_2";
    public static final String NAME_3 = "name_3";
    public static final String NAME_4 = "name_4";
    private static final int[] TO = null;
    public static List<Map<String, String>> PASSENGER_LIST = null;
    public static Map<String, String[]> PASSENGER_MAP = null;
    private static final String TAG = "SubmitOrderActivity";
    public static List<Map<String, Object>> TICKET_INFO_LIST;
    public static Map<String, Object> TICKET_INFO_MAP;
    private Button bt_selectPassenger;
    private Button bt_submit;
    private ListView lv_selectPassenger;
    private ListView lv_selectSeatType;
    private ListView lv_ticketInfo;
    private TableLayout tb_ticketInfo;
    private TextView tv_stationTrainCode;

    public SubmitOrderActivity() {
    }



    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_submit_order);
        initCanTicketType((BaseQueryLeft) getIntent().getSerializableExtra("ticket_info"));
        init();
    }

    public void initCanTicketType(BaseQueryLeft baseQueryLeft) {
        StringBuffer sb = new StringBuffer();
        if ((!baseQueryLeft.getYz_num().equals("\u65e0")) && (!baseQueryLeft.getYz_num().equals("--"))) {
            sb.append("\u786c\u5ea7,");
        }
        if ((!baseQueryLeft.getRz_num().equals("\u65e0")) && (!baseQueryLeft.getRz_num().equals("--"))) {
            sb.append("\u8f6f\u5ea7,");
        }
        if ((!baseQueryLeft.getYw_num().equals("\u65e0")) && (!baseQueryLeft.getYw_num().equals("--"))) {
            sb.append("\u786c\u5367,");
        }
        if ((!baseQueryLeft.getRw_num().equals("\u65e0")) && (!baseQueryLeft.getRw_num().equals("--"))) {
            sb.append("\u8f6f\u5367,");
        }
        if ((!baseQueryLeft.getGr_num().equals("\u65e0")) && (!baseQueryLeft.getGr_num().equals("--"))) {
            sb.append("\u9ad8\u7ea7\u8f6f\u5367,");
        }
        if ((!baseQueryLeft.getZy_num().equals("\u65e0")) && (!baseQueryLeft.getZy_num().equals("--"))) {
            sb.append("\u4e00\u7b49\u5ea7,");
        }
        if ((!baseQueryLeft.getZe_num().equals("\u65e0")) && (!baseQueryLeft.getZe_num().equals("--"))) {
            sb.append("\u4e8c\u7b49\u5ea7,");
        }
        if ((!baseQueryLeft.getTz_num().equals("\u65e0")) && (!baseQueryLeft.getTz_num().equals("--"))) {
            sb.append("\u7279\u7b49\u5ea7,");
        }
        if ((!baseQueryLeft.getSwz_num().equals("\u65e0")) && (!baseQueryLeft.getSwz_num().equals("--"))) {
            sb.append("\u5546\u52a1\u5ea7,");
        }
        CAN_SEAT_TYPE = sb.toString();
    }

    public void init() {
        PASSENGER_MAP = new HashMap();
        PASSENGER_LIST = new ArrayList();
        TICKET_INFO_LIST = new ArrayList();
        TICKET_INFO_MAP = new HashMap();
        Map<String, String> m = new HashMap<String, String>();

        int row_num = 0;

        Iterator<Passenger> it = CommunalData.PASSENGER_LIST.iterator();
        Log.v(TAG, "SIZE OF PASSERGER" + CommunalData.PASSENGER_LIST.size());
        while (it.hasNext()) {
            Passenger p = it.next();
            if (row_num == 4) {
                Log.v("SubmitOrderActivity", "4M" + m);
                PASSENGER_LIST.add(m);
                m = new HashMap();
                row_num = 0;
            }
            Log.v("SubmitOrderActivity", p.getPassenger_name());
            m.put(FROM[row_num], p.getPassenger_name());
            HashMap<String, String> sub = new HashMap<String, String>();
            sub.put(p.getPassenger_id_no(), p.getPassenger_type_name());
            PASSENGER_MAP.put(p.getPassenger_name(), new String[]{p.getPassenger_id_no(), p.getPassenger_type_name()});
            Log.v("SubmitOrderActivity", FROM[row_num]);
            row_num = row_num + 1;
        }
        Log.v("SubmitOrderActivity", PASSENGER_LIST + "");
        initView();
    }

    public void initView() {
        tb_ticketInfo = (TableLayout) findViewById(R.id.tb_submitOrder_ticketInfo);
        tv_stationTrainCode = (TextView) findViewById(R.id.tv_submitOrder_station_train_code);
        lv_selectPassenger = (ListView) findViewById(R.id.lv_selectPassenger);
        lv_ticketInfo = (ListView) findViewById(R.id.lv_submitOrder_ticketInfo);
        bt_submit = (Button) findViewById(R.id.bt_submit);
        tv_stationTrainCode.setText(ShowTicketDetail.SUBMIT_BASEDATA.getQueryLeftNewDTO().getStation_train_code());
        lv_selectPassenger.setAdapter(new com.cheart.do12306.app.adapter.SubmitOrderSelectPassengerAdapter(this, PASSENGER_LIST, R.layout.submit_order_select_passenger_item,FROM, TO));
        lv_selectPassenger.setOnItemClickListener(new AdapterView.OnItemClickListener() {

            public void onItemClick(AdapterView<?> adapterView, View view, int i, long l) {
                //Toast.makeText(this, "" + i, 0x1).show();
            }
        });
        bt_submit.setOnClickListener(new View.OnClickListener() {

            public void onClick(View view) {
                new SubmitOrderTask(SubmitOrderActivity.this).execute(new String[0x0]);
            }
        });
    }

    public void updateView() {
        // :( Parsing error. Please contact me.
    }



//
//
//    public View getView(int position, View convertView, ViewGroup parent) {
//        SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder holder = 0x0;
//        if (holder == null) {
//            SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder holder = new SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder(this, 0x0);
//            LayoutInflater li = (LayoutInflater) context.getSystemService("layout_inflater");
//            convertView = li.inflate(0x7f030033, 0x0);
//            SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_1 = holder;
//            SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_2 = holder;
//            SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_3 = holder;
//            SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_4 = holder;
//        } else {
//            holder = convertView.getTag();
//        }
//        com.cheart.do12306.app.adapter.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_1.setText((Map) data.get(position).get("name_1").toString());
//        SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_2.setText((Map) data.get(position).get("name_2").toString());
//        SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_3.setText((Map) data.get(position).get("name_3").toString());
//        SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_4.setText((Map) data.get(position).get("name_4").toString());
//        SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_1.setOnCheckedChangeListener(new SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.NameCheckedChangeListener(this));
//        SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_2.setOnCheckedChangeListener(new SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.NameCheckedChangeListener(this));
//        SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_3.setOnCheckedChangeListener(new SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.NameCheckedChangeListener(this));
//        SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_4.setOnCheckedChangeListener(new SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.NameCheckedChangeListener(this));
//        SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_1.setOnClickListener(SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.listener);
//        SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_2.setOnClickListener(SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.listener);
//        SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_3.setOnClickListener(SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.listener);
//        SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.ck_name_4.setOnClickListener(SubmitOrderActivity.SubmitOrderSelectPassengerAdapter.ViewHolder.listener);
//        convertView.setTag(holder);
//        return convertView;
//    }

    class NameCheckedChangeListener implements CompoundButton.OnCheckedChangeListener {

        public void onCheckedChanged(CompoundButton compoundButton, boolean b) {
            // :( Parsing error. Please contact me.
        }
    }

    class NameClickListener implements View.OnClickListener {

        public void onClick(View view) {
        }
    }
}



class NameCheckedChangeListener implements CompoundButton.OnCheckedChangeListener {

    public void onCheckedChanged(CompoundButton compoundButton, boolean b) {
        // :( Parsing error. Please contact me.
    }
}

class NameClickListener implements View.OnClickListener {

    public void onClick(View view) {
    }
}


class SubmitOrderSelectPassengerAdapter extends SimpleAdapter {
    List<? extends Map<String, ?>> data;
    Context context;
    public SubmitOrderSelectPassengerAdapter(Context context,
                                             List<? extends Map<String, ?>> data,
                                             int resource,
                                             String[] from,
                                             int[] to) {
        super(context, data, resource, from, to);
        this.data = data;
        this.context = context;
    }

    @Override
    public int getCount() {
        return data.size();
    }

    @Override
    public Object getItem(int position) {
        return data.get(position);
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    private class ViewHolder {
        private CheckBox ck_name_1;
        private CheckBox ck_name_2;
        private CheckBox ck_name_3;
        private CheckBox ck_name_4;

    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {

        ViewHolder holder = null;
        if (holder == null){
            holder = new ViewHolder();
            LayoutInflater li = (LayoutInflater) context.getSystemService(Context.
                    LAYOUT_INFLATER_SERVICE);
            convertView = li.inflate(R.layout.submit_order_select_passenger_item, null);

            holder.ck_name_1 = (CheckBox) convertView.findViewById(R.id.
                    tv_submitOrder_selectPassenger_name_1);
            holder.ck_name_2 = (CheckBox) convertView.findViewById(R.id.
                    tv_submitOrder_selectPassenger_name_2);
            holder.ck_name_3 = (CheckBox) convertView.findViewById(R.id.
                    tv_submitOrder_selectPassenger_name_3);
            holder.ck_name_4 = (CheckBox) convertView.findViewById(R.id.
                    tv_submitOrder_selectPassenger_name_4);

        } else {
            holder = (ViewHolder) convertView.getTag();
        }

        holder.ck_name_1.setText(data.get(position).get("name_1").toString());
        holder.ck_name_2.setText(data.get(position).get("name_2").toString());
        holder.ck_name_3.setText(data.get(position).get("name_3").toString());
        holder.ck_name_4.setText(data.get(position).get("name_2").toString());

        convertView.setTag(holder);
        return convertView;
    }



}

